// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtnQz9Mcbz9XEzs1vzlkkG7ZV3KnTouiw',
    appId: '1:616106779952:web:a206cb69f2f7364fb154f5',
    messagingSenderId: '616106779952',
    projectId: 'may-d08ee',
    authDomain: 'may-d08ee.firebaseapp.com',
    storageBucket: 'may-d08ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYnWJsP2NIyEFjeTcDcYShBUZHlcKjI8',
    appId: '1:616106779952:android:dea8b45d97db45fcb154f5',
    messagingSenderId: '616106779952',
    projectId: 'may-d08ee',
    storageBucket: 'may-d08ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtk6YV4YGUHAkEyZR7OOrvcu-zg3DFfvg',
    appId: '1:616106779952:ios:5b53fe7b0613d939b154f5',
    messagingSenderId: '616106779952',
    projectId: 'may-d08ee',
    storageBucket: 'may-d08ee.firebasestorage.app',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtk6YV4YGUHAkEyZR7OOrvcu-zg3DFfvg',
    appId: '1:616106779952:ios:5b53fe7b0613d939b154f5',
    messagingSenderId: '616106779952',
    projectId: 'may-d08ee',
    storageBucket: 'may-d08ee.firebasestorage.app',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtnQz9Mcbz9XEzs1vzlkkG7ZV3KnTouiw',
    appId: '1:616106779952:web:4f527c972305af54b154f5',
    messagingSenderId: '616106779952',
    projectId: 'may-d08ee',
    authDomain: 'may-d08ee.firebaseapp.com',
    storageBucket: 'may-d08ee.firebasestorage.app',
  );
}
